### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by Lo2David** [webgeodatavore/openmaptiles-geo-data-gouv-fr#1]
Hello
Constatant qu'il y a peu d'actualité récente sur ce pourtant intéressant projet, j'aimerai savoir si les couches diffusées continuent à être régulièrement mises à jour ?
Sincères salutations

**Comment by ThomasG77** [comment]
Oui, toutes les semaines pour les tuiles vecteur.
Il n'est pas lié au service de tuiles maintenu par la DINUM.
PS: ce projet est maintenu à part sans lien avec la mise à jour des tuiles vecteur qui permettent d'avoir les fonds de plan
